export type PregnancyWeekData = {
    week: number
    trimester: number
    size: string
    weight: string
    fruit: string
    development: string
    tips: string
}

// Données générées pour l'exemple (à enrichir avec du contenu médical validé)
export const pregnancyWeeksData: Record<number, PregnancyWeekData> = {
    // Semaines 1-4
    4: {
        week: 4,
        trimester: 1,
        size: "2 mm",
        weight: "< 1 g",
        fruit: "Graine de pavot",
        development: "Le blastocyste s'implante dans l'utérus. Le placenta commence à se former.",
        tips: "Commencez à prendre de l'acide folique si ce n'est pas déjà fait.",
    },
    5: {
        week: 5,
        trimester: 1,
        size: "3 mm",
        weight: "< 1 g",
        fruit: "Graine de sésame",
        development: "Le tube neural se forme, préfigurant le cerveau et la moelle épinière. Le cœur commence à battre.",
        tips: "Évitez l'alcool, le tabac et réduisez la caféine.",
    },
    6: {
        week: 6,
        trimester: 1,
        size: "5 mm",
        weight: "< 1 g",
        fruit: "Lentille",
        development: "Le visage commence à prendre forme. Les bourgeons des bras et des jambes apparaissent.",
        tips: "Les nausées peuvent apparaître. Mangez de petites quantités fréquemment.",
    },
    7: {
        week: 7,
        trimester: 1,
        size: "1 cm",
        weight: "< 1 g",
        fruit: "Myrtille",
        development: "Le cerveau grandit rapidement. Les reins commencent à se former.",
        tips: "Buvez beaucoup d'eau pour rester hydratée.",
    },
    8: {
        week: 8,
        trimester: 1,
        size: "1.6 cm",
        weight: "1 g",
        fruit: "Framboise",
        development: "Les doigts et les orteils commencent à se former, bien qu'encore palmés.",
        tips: "Prévoyez votre premier rendez-vous prénatal.",
    },
    9: {
        week: 9,
        trimester: 1,
        size: "2.3 cm",
        weight: "2 g",
        fruit: "Olive",
        development: "Les muscles se forment, bébé commence à bouger (mais vous ne le sentez pas encore).",
        tips: "Portez un soutien-gorge confortable si votre poitrine est sensible.",
    },
    10: {
        week: 10,
        trimester: 1,
        size: "3.1 cm",
        weight: "4 g",
        fruit: "Pruneau",
        development: "Les organes vitaux sont en place. La queue embryonnaire disparaît.",
        tips: "Faites attention aux infections urinaires, fréquentes à ce stade.",
    },
    11: {
        week: 11,
        trimester: 1,
        size: "4.1 cm",
        weight: "7 g",
        fruit: "Figue",
        development: "Bébé commence à ouvrir et fermer les poings. Les bourgeons dentaires apparaissent.",
        tips: "Continuez à manger équilibré, riche en calcium et protéines.",
    },
    12: {
        week: 12,
        trimester: 1,
        size: "5.4 cm",
        weight: "14 g",
        fruit: "Citron vert",
        development: "Les ongles se forment. Le visage a une apparence plus humaine.",
        tips: "C'est souvent le moment de l'échographie du premier trimestre.",
    },
    13: {
        week: 13,
        trimester: 1,
        size: "7.4 cm",
        weight: "23 g",
        fruit: "Gousse de petit pois",
        development: "Les empreintes digitales se forment. Bébé peut avaler du liquide amniotique.",
        tips: "Le risque de fausse couche diminue considérablement.",
    },
    14: {
        week: 14,
        trimester: 2,
        size: "8.7 cm",
        weight: "43 g",
        fruit: "Citron",
        development: "Bébé peut faire des grimaces. Les reins produisent de l'urine.",
        tips: "Vous vous sentirez probablement plus énergique au deuxième trimestre.",
    },
    15: {
        week: 15,
        trimester: 2,
        size: "10.1 cm",
        weight: "70 g",
        fruit: "Pomme",
        development: "Bébé perçoit la lumière à travers ses paupières fermées. Les jambes grandissent.",
        tips: "Dormez sur le côté gauche pour améliorer la circulation.",
    },
    16: {
        week: 16,
        trimester: 2,
        size: "11.6 cm",
        weight: "100 g",
        fruit: "Avocat",
        development: "Le cœur bat vigoureusement. Le système nerveux continue de se développer.",
        tips: "Vous pourriez commencer à sentir les premiers mouvements (bulles).",
    },
    17: {
        week: 17,
        trimester: 2,
        size: "13 cm",
        weight: "140 g",
        fruit: "Poire",
        development: "Le squelette passe du cartilage à l'os. Le cordon ombilical s'épaissit.",
        tips: "Faites attention à votre posture pour éviter les maux de dos.",
    },
    18: {
        week: 18,
        trimester: 2,
        size: "14.2 cm",
        weight: "190 g",
        fruit: "Poivron",
        development: "Les oreilles sont en place. Bébé peut entendre vos bruits internes.",
        tips: "C'est le moment de l'échographie morphologique (souvent entre 18 et 22 SA).",
    },
    19: {
        week: 19,
        trimester: 2,
        size: "15.3 cm",
        weight: "240 g",
        fruit: "Mangue",
        development: "Le vernix caseosa se développe pour protéger la peau de bébé.",
        tips: "Hydratez votre peau pour prévenir les vergetures.",
    },
    20: {
        week: 20,
        trimester: 2,
        size: "16.4 cm",
        weight: "300 g",
        fruit: "Banane",
        development: "Vous êtes à mi-chemin ! Bébé avale plus de liquide amniotique pour exercer son système digestif.",
        tips: "Faites attention à votre apport en fer.",
    },
    21: {
        week: 21,
        trimester: 2,
        size: "26.7 cm",
        weight: "360 g",
        fruit: "Carotte",
        development: "Les sourcils et les paupières sont complètement formés.",
        tips: "Surveillez les signes d'œdème (gonflement) aux pieds et chevilles.",
    },
    22: {
        week: 22,
        trimester: 2,
        size: "27.8 cm",
        weight: "430 g",
        fruit: "Courge spaghetti",
        development: "Les yeux sont formés mais l'iris n'a pas encore de pigmentation. Le sens du toucher se développe.",
        tips: "Reposez-vous suffisamment et évitez de rester debout trop longtemps.",
    },
    23: {
        week: 23,
        trimester: 2,
        size: "28.9 cm",
        weight: "500 g",
        fruit: "Gros pamplemousse",
        development: "Le bébé peut maintenant entendre votre voix et les battements de votre cœur de façon plus distincte.",
        tips: "Commencez à lire des histoires ou à chanter des berceuses.",
    },
    24: {
        week: 24,
        trimester: 2,
        size: "30 cm",
        weight: "600 g",
        fruit: "Épi de maïs",
        development: "Les poumons continuent de se développer. Les bourgeons gustatifs se forment.",
        tips: "Test de dépistage du diabète gestationnel souvent réalisé autour de cette période.",
    },
    25: {
        week: 25,
        trimester: 2,
        size: "34.6 cm",
        weight: "660 g",
        fruit: "Chou-fleur",
        development: "La graisse commence à s'accumuler sous la peau, lissant les rides.",
        tips: "Si vous avez des crampes aux jambes, étirez-vous et hydratez-vous.",
    },
    26: {
        week: 26,
        trimester: 2,
        size: "35.6 cm",
        weight: "760 g",
        fruit: "Laitue",
        development: "Bébé commence à ouvrir les yeux. Il réagit aux bruits forts.",
        tips: "Mangez des aliments riches en fibres pour éviter la constipation.",
    },
    27: {
        week: 27,
        trimester: 3,
        size: "36.6 cm",
        weight: "875 g",
        fruit: "Chou-fleur",
        development: "Le cerveau montre une activité d'ondes cérébrales. Bébé a des horaires de sommeil réguliers.",
        tips: "Bienvenue au troisième trimestre !",
    },
    28: {
        week: 28,
        trimester: 3,
        size: "37.6 cm",
        weight: "1 kg",
        fruit: "Aubergine",
        development: "Bébé peut cligner des yeux. Les cils sont présents.",
        tips: "Si votre rhésus est négatif, vous pourriez recevoir une injection de RhoGAM.",
    },
    29: {
        week: 29,
        trimester: 3,
        size: "38.6 cm",
        weight: "1.15 kg",
        fruit: "Courge butternut",
        development: "La tête grossit pour accommoder le cerveau en développement.",
        tips: "Consommez suffisamment de calcium pour le développement osseux de bébé.",
    },
    30: {
        week: 30,
        trimester: 3,
        size: "39.9 cm",
        weight: "1.3 kg",
        fruit: "Chou",
        development: "La moelle osseuse produit maintenant les globules rouges.",
        tips: "Surélevez vos jambes pour réduire le gonflement.",
    },
    31: {
        week: 31,
        trimester: 3,
        size: "41.1 cm",
        weight: "1.5 kg",
        fruit: "Noix de coco",
        development: "Bébé tourne la tête d'un côté à l'autre. Il perçoit bien les signaux des 5 sens.",
        tips: "Pratiquez des exercices de respiration pour la préparation à l'accouchement.",
    },
    32: {
        week: 32,
        trimester: 3,
        size: "42.4 cm",
        weight: "1.7 kg",
        fruit: "Jicama",
        development: "Les ongles des orteils sont complètement formés. Le duvet (lanugo) commence à tomber.",
        tips: "Voyez votre médecin toutes les deux semaines à partir de maintenant.",
    },
    33: {
        week: 33,
        trimester: 3,
        size: "43.7 cm",
        weight: "1.9 kg",
        fruit: "Ananas",
        development: "Le système immunitaire se renforce. Les os durcissent, sauf ceux du crâne.",
        tips: "Pensez à préparer votre valise de maternité.",
    },
    34: {
        week: 34,
        trimester: 3,
        size: "45 cm",
        weight: "2.1 kg",
        fruit: "Cantaloup",
        development: "La couche de vernix s'épaissit. Les testicules descendent (pour les garçons).",
        tips: "Familiarisez-vous avec les signes du travail.",
    },
    35: {
        week: 35,
        trimester: 3,
        size: "46.2 cm",
        weight: "2.4 kg",
        fruit: "Melon miel",
        development: "Les reins sont complètement développés. Le lever est rapide.",
        tips: "Faites le point sur votre projet de naissance.",
    },
    36: {
        week: 36,
        trimester: 3,
        size: "47.4 cm",
        weight: "2.6 kg",
        fruit: "Laitue romaine",
        development: "La peau devient plus lisse. Bébé descend dans le bassin (allègement).",
        tips: "Visites prénatales hebdomadaires maintenant.",
    },
    37: {
        week: 37,
        trimester: 3,
        size: "48.6 cm",
        weight: "2.9 kg",
        fruit: "Blette",
        development: "Considéré comme à terme précoce. Les poumons sont matures.",
        tips: "Surveillez la perte du bouchon muqueux.",
    },
    38: {
        week: 38,
        trimester: 3,
        size: "49.8 cm",
        weight: "3 kg",
        fruit: "Poireaux",
        development: "Les organes sont prêts à fonctionner en dehors de l'utérus.",
        tips: "Reposez-vous autant que possible avant le grand jour.",
    },
    39: {
        week: 39,
        trimester: 3,
        size: "50.7 cm",
        weight: "3.3 kg",
        fruit: "Mini pastèque",
        development: "La croissance ralentit. La peau est rosée.",
        tips: "Surveillez les contractions régulières.",
    },
    40: {
        week: 40,
        trimester: 3,
        size: "51.2 cm",
        weight: "3.5 kg",
        fruit: "Citrouille",
        development: "C'est le jour J (théorique) ! Bébé est prêt à vous rencontrer.",
        tips: "Bonne rencontre !",
    },
    41: {
        week: 41,
        trimester: 3,
        size: "51.7 cm",
        weight: "3.6 kg",
        fruit: "Citrouille",
        development: "Bébé continue de prendre un peu de poids. Surveillance accrue.",
        tips: "Patience, bébé arrivera quand il sera prêt !",
    },
    42: {
        week: 42,
        trimester: 3,
        size: "52 cm",
        weight: "3.7 kg",
        fruit: "Pastèque",
        development: "Dépassement de terme. Surveillance rapprochée ou déclenchement envisagé.",
        tips: "Discutez avec votre équipe médicale des options.",
    }
}

export function getWeekData(week: number): PregnancyWeekData {
    // Fallback sur la semaine la plus proche si données manquantes
    const safeWeek = Math.max(4, Math.min(week, 42))
    return pregnancyWeeksData[safeWeek] || pregnancyWeeksData[4]
}
